### ISSUE TITLE
Sourcemaps and style elements

### ISSUE THREAD

**Issue by xdissent** [nodys/cssy#1]
I couldn't get the browser to recognize source maps for injected CSS. I didn't do much poking around but perhaps they're not supported for inlined `style` elements? I changed the `CssyBrowser.insert()` method to instead create a `link` element and add the source as a data URI. That seemed to fix sourcemaps for me. Here's the `update` function that creates the data URI:
```js
function update(src) {
  var uri = 'data:text/css;base64,' + new Buffer(src).toString('base64');
  element.setAttribute('href', uri);
}
```
Do you see any problems with using `link` + data-uri rather than `style` + text-node? Does the current method work for you? I can send a PR if interested.

**Comment by nopnop** [comment]
Hello @xdissent,
I close this issue for now, but let me know if you think it's still relevant.
