### ISSUE TITLE
Trouble parsing Stylus

### ISSUE THREAD

**Issue by antoniobrandao** [nodys/cssy#2]
I'm using the stylus parser to read my .styl files, but I get this error:

    error: src/stylus/pages/dashboard.styl:9:1: Unclosed block (Try to use appropriate parser for styl) while parsing file: /Users/antoniobrandao/WEBROOT/ABWA/src/stylus/pages/dashboard.styl

This is my config

    "browserify": {
      "transform": [
        [ "cssy", { "parser": [ "./node_modules/cssy/lib/parsers/stylus.js" ] } ]
      ]
    },

Here is how I'm loading the stylus file

    var cssy = require('cssy')
    
    cssy.config({
      minify:  false,
      sourcemap: true
    })
    
    cssy.require( '../../stylus/pages/dashboard.styl' );

I know the parser file (stylus.js) is being reached because I can log.console from there. Any ideas?

**Comment by nopnop** [comment]
Hi @antoniobrandao,

1. You need to install stylus: `npm install --save stylus` and the last cssy package `npm install --save cssy@latest`
2. In your `package.json` (the "parser" key is only required to provide your own parser):
    ```
    "browserify": {
      "transform": [ "cssy"]
    }
    ```

This is enough to use stylus source in your browser source. Just remember that this source must be bundled with [browserify](http://browserify.org/). For instance with  :

**application.js**:
```javascript
var dashboard = require('./dashboard.styl');
dashboard(); // Inject dashboard - this is like for dashboard.insert(document.head)
```

**./dashboard.styl**:
```css
.dashboard
  background: red
```

Then you can use browserify (`npm install -g browserify`) to create a bundle:
```shell
browserify application.js > bundle.js
```

I made a gist: https://gist.github.com/nopnop/a1200c339d626b83676a
See too a server exemple with live reload: https://github.com/nodys/cssy/tree/master/exemples
