### ISSUE TITLE
Generating a single css bundle when all requires have been processed.

### ISSUE THREAD

**Issue by pleunv** [nodys/cssy#4]
Hello there!

I'm looking into cssy with as goal generating a single output bundle based on all required() css files in my project, instead of injecting script tags inside each separate (React) component, but I'm not really sure how to achieve this behavior :).

Right now I've got it set up with postcss, in a similar fashion as described in the docs:

``` javascript
function _postcss(ctx, done) {
    var result = postcss()
        .use(customProperties())
        .use(postcssCalc())
        .use(autoprefixer.postcss)
        .process(ctx.src, {
            map: { prev: ctx.map }
        });

    ctx.src = result.css;
    ctx.map = result.map.toJSON();

    done(null, ctx);
}

b.plugin(cssy, {
    minify: true,
    sourcemaps: true,
    remedy: {
        processor: _postcss,
        match:     /css$/i,
        import:    false
    }
})
```

This is correctly running postcss on each css require() that browserify encounters in my components. However, I'd like to be able to write this to a single bundle file upon completion. Would this be possible, and what would the best approach be?

**Comment by nopnop** [comment]
Hello @pleunv,

To make sure I understand well your goal: You want to create a bundle that *only* contain all the css sources required in your project *and* in its dependencies (inside node_modules)? Your css bundle, must be a css file with only css source transformed by postcss, and your browserify bundle must not contain the css source, only your components. Am I right?

**Comment by pleunv** [comment]
Yes, thats correct :). I'm basically trying to mimic the ExtractTextPlugin behavior you have in Webpack, but in Browserify instead. As far as I can see Cssy has the resolving & processing part down, but I can't really figure out a way to bundle up the processed css files into a single bundle.css.

**Comment by nopnop** [comment]
Hello @pleunv,

Maybe, cssy is not the right tool for you needs. Cssy purpose is to expose a js module for each css source. This can not be achieved with an external css bundle.  Anyway, what you looking for is quite useful too, so, I made a gist for you :) 
https://gist.github.com/nopnop/ad98a1f9cd2281a257e1

It is almost a complete package, clone it, run npm install and see [example.js](https://gist.github.com/nopnop/ad98a1f9cd2281a257e1#file-example-js) and [xcssy.js](https://gist.github.com/nopnop/ad98a1f9cd2281a257e1#file-xcssy-js). 

[xcssy.js](https://gist.github.com/nopnop/ad98a1f9cd2281a257e1#file-xcssy-js) is a browserify plugin. Here how it works:
1) Add a browserify transform to handle all css module ([xcssy.js#44](https://gist.github.com/nopnop/ad98a1f9cd2281a257e1#file-xcssy-js-L44))
2) Remove css source from browserify module  ([xcssy.js#56](https://gist.github.com/nopnop/ad98a1f9cd2281a257e1#file-xcssy-js-L56))
3) Apply some transformations to the css source ([xcssy.js#59](https://gist.github.com/nopnop/ad98a1f9cd2281a257e1#file-xcssy-js-L59)) and store the result with the source map ([xcssy.js#70](https://gist.github.com/nopnop/ad98a1f9cd2281a257e1#file-xcssy-js-L70))
4) Once the browserify bundle is finished (we listen to the bundle event that expose the bundle stream),  we write down the css bundle ([xcssy.js#80](https://gist.github.com/nopnop/ad98a1f9cd2281a257e1#file-xcssy-js-L80))

I can release this as a package if you want.

**Comment by pleunv** [comment]
Oh that's brilliant, thank you so much :). I'll play around a bit with this next week.
